defaults:
  - attribution_method: flipd
  - _self_

out_dir: ./outputs
name: laion-lid-estimates-sd-upscaler-conditional-ai-0.05
seed: 0

lora_path: null # ../diffusers/examples/dreambooth/lora-trained-xl-prior_preservation/pytorch_lora_weights.safetensors

model:
  model_class: local_deepfloyd_if_pipeline.LocalStableDiffusionUpscalePipeline
  model_id: stabilityai/stable-diffusion-x4-upscaler # stabilityai/sdxl-turbo
  # num_inference_steps: 4
  guidance_scale: 9.0
  # image_size: 512
  device_map:
    # text encoder
    "text_model": 3

    # VAE
    "encoder": 3
    "decoder": 3
    "quant_conv": 3
    "post_quant_conv": 3

    # UNet
    "text_projection": 0
    "add_embedding": 0
    "time_embedding": 0

    "conv_in": 0

    "down_blocks": 1
    "mid_block": 0
    "up_blocks.0": 2
    "up_blocks.1": 0
    "up_blocks.2": 3
    "up_blocks.3": 2

    "conv_norm_out": 0
    "conv_out": 0

    "class_embedding": 0

conditional: true
dataset_path: /net/scratch/hscra/plgrid/plgpawel269/LID-project/data/laion-2b-1024x1024
caption_file: captions_ai.json
prompt_start_idx: 0
prompt_end_idx: 1000 # no limits
