defaults:
  - _self_

out_dir: /data/pskiers/concept_dimention/
name: sdxl-with-interventions-monster
seed: 0

model:
  model_class: custom_pipelines.local_sdxl_pipeline.LocalStableDiffusionXLPipeline
  model_id: sdxl-dmd # stabilityai/stable-diffusion-xl-base-1.0 # stabilityai/sdxl-turbo
  lora_path: null # ../diffusers/examples/dreambooth/lora-trained-xl-prior_preservation/pytorch_lora_weights.safetensors
  device_map: null
  num_inference_steps: 4
call_kwargs:
  num_inference_steps: 4
  guidance_scale: 0.0
  timesteps: [999, 749, 499, 249]

prompt: "A picture of a monster"
token: "monster"
min_intervention_strenght: 25
max_intervention_strenght: 45
num_random_directions: 3

batch_size: 3
num_samples: 10000
directions_path: "../universal-diffsae/sae-ckpts/monster-k32-exp-factor-8_grads"
direction_type: "sae"

