defaults:
  - _self_

out_dir: /net/scratch/hscra/plgrid/plgekaczmarczyk/LID-project/diffusion_memorization/outputs
name: sdxl-with-interventions-character
seed: 0

model:
  model_class: custom_pipelines.local_sdxl_pipeline.LocalStableDiffusionXLPipeline
  model_id: sdxl-dmd # stabilityai/stable-diffusion-xl-base-1.0 # stabilityai/sdxl-turbo
  lora_path: null # ../diffusers/examples/dreambooth/lora-trained-xl-prior_preservation/pytorch_lora_weights.safetensors
  device_map: null
  num_inference_steps: 4
call_kwargs:
  num_inference_steps: 4
  guidance_scale: 0.0
  timesteps: [999, 749, 499, 249]

prompt: "a building in a stunning landscape in the style of a famous artist"
target_tokens: ["in", "the", "style", "of", "a", "famous", "artist"]
min_intervention_strenght: 8
max_intervention_strenght: 8
num_random_directions: 2

batch_size: 9
num_samples: 12006
directions_path: "../universal-diffsae/sae-ckpts/monster-k32-exp-factor-8_grads"
direction_type: "sae"

